default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: overtime_development
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: overtime_test
  pool: 5
  username: postgres
  password: root

production:
  <<: *default
  database: Overtime_production
  username: Overtime
  password: <%= ENV['OVERTIME_DATABASE_PASSWORD'] %>
